a new backend project
ArnonEilat/kueen-b pull request #11
Opened 2022-03-20 09:06 UTC by ShirAmit96

2022-03-20 09:33 UTC, ArnonEilat requested changes
Good Job

2022-03-20 09:33 UTC, ArnonEilat commented on backend/app.js
> +var app = express();
Don't use `var`.
Use `const` or `let`.
```suggestion
const app = express();
```

https://stackoverflow.com/questions/762011/whats-the-difference-between-using-let-and-var

2022-03-20 09:33 UTC, ArnonEilat commented on backend/app.js
> +app.listen(3000, function () {
Arrow functions is less error prone:
```suggestion
app.listen(3000, () => {
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

2022-03-20 09:33 UTC, ArnonEilat commented on backend/package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
There is a convention about npm packages:
Running `npm start` should start a package.

```suggestion
    "start": "node app.js"
```

https://docs.npmjs.com/cli/v8/commands/npm-start

2022-03-23 19:33 UTC, ArnonEilat approved these changes

2022-03-24 08:30 UTC, katz-tom approved these changes

2022-03-24 08:34 UTC, merged